apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      imagePullSecrets:
        - name: jfrog-registry-secret
      containers:
        - name: addressbook
          image: localhost:8046/github_poc_jfrog/addressbook:latest
          ports:
            - containerPort: 8080
