name: Java Maven Example for GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

#      - name: Log in to DockerHub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to JFrog Artifactory
        run: echo ${{ secrets.JFROG_ACCESS_TOKEN}} | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/addressbook:latest .

      - name: Push Docker image to Artifactory
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/addressbook:latest

#      - name: JFrog Xray scan
#        uses: jfrog/setup-jfrog-cli@v4
#        with:
#          version: latest
#
#      - name: Run Xray scan on Docker image
#        run: |
#          jfrog rt docker-scan ${{ secrets.DOCKER_REGISTRY }}/addressbook:latest --scan-type xray
#        env:
#          JFROG_URL: ${{ secrets.JFROG_URL }}
#          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
#          JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}


