name: Java Maven Example for GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package\

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      #      - name: Log in to DockerHub
      #        uses: docker/login-action@v3
      #        with:
      #          username: ${{ secrets.DOCKER_USERNAME }}
      #          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to JFrog Artifactory
#        uses: docker/login-action@v2
        run: docker login -u admin -p Turbo3114! http://127.0.0.1:8046
#        run: echo ${{ secrets.JFROG_ACCESS_TOKEN}} | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.JFROG_USERNAME }} --password-stdin?
#        with:
#         registry: http://127.0.0.1:8046
#         username: admin
#         password: Turbo3114!

      - name: Build Docker image
        run: docker build -t localhost:8046/github_poc_jfrog/addressbook:latest .

      - name: Push Docker image to Artifactory
        run: docker push localhost:8046/github_poc_jfrog/addressbook:latest

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          project_id: heroic-arbor-431706-b1
          create_credentials_file: true
          workload_identity_provider: projects/402394263593/locations/global/workloadIdentityPools/githubactions/providers/githubactions
          service_account:  poc-service-account@heroic-arbor-431706-b1.iam.gserviceaccount.com
          #  credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: |
          gcloud info

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      #      - name: Check fro cluster existence
      #        id: check-cluster
      #        run: |
      #          if gcloud container clusters describe poc-github-cluster --zone us-central1-a --project heroic-arbor-431706-b1 >/dev/null 2>&1; then
      #          echo "Cluster already exists, skipping creation."
      #          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }}
      #          kubectl get nodes
      #          exit 0
      #          else
      #          echo "Cluster does not exist, creating now."
      #          fi

      - name: Configure kubectl for GKE
        #        if: ${{ !steps.check-cluster.outcome == 'success' }}
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }}

      #      - name: JFrog Xray scan
      #        uses: jfrog/setup-jfrog-cli@v4
      #        with:
      #          version: latest
      #
      #      - name: Run Xray scan on Docker image
      #        run: |
      #          jfrog rt docker-scan ${{ secrets.DOCKER_REGISTRY }}/addressbook:latest --scan-type xray
      #        env:
      #          JFROG_URL: ${{ secrets.JFROG_URL }}
      #          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      #          JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}

      #      - name: Authenticate to GKE
      #        run: |
      #          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ${HOME}/gcloud.json
      #          gcloud auth activate-service-account --key-file=${HOME}/gcloud.json
      #          gcloud config set project ${{ secrets.GKE_PROJECT_ID }}
      #          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }}

      # Step 12: Pull the Docker image from JFrog
      - name: Pull Docker image from JFrog
        run: |
          docker pull localhost:8046/github_poc_jfrog/addressbook:latest

      # Step 13: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      # Optional: Verify deployment
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
